# Generated by Django 5.2.6 on 2026-03-05 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['date_added']},
        ),
    ]
